<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>5b0e6646-5da7-4e8d-93df-5873f68048b0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspireApp1.ApiService\AspireApp1.ApiService.csproj" />
    <ProjectReference Include="..\AspireApp1.Web\AspireApp1.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="8.0.0" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="8.0.0" />
  </ItemGroup>

</Project>
